name: SonarCloud Analysis

on:
  push:
    branches:
      - '**'           # Run on all branches
  pull_request:
    branches:
      - '**'           # Run on all PRs too

jobs:
  sonarqube:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Java (required by SonarCloud scanner)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          projectBaseDir: .   # Adjust if your project is in a subfolder
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
